- src/lib/const/firebaseNode.ts
- src/lib/firebaseNode.ts
- src/lib/types/DatabaseNodeType.ts
- src/lib/types/FirebaseNodeType.ts
- src/nodes/database.ts
- src/nodes/firebase-in.ts
- test/firebase-in_spec.js
Prevents the unsubscription of a listener if it is still used in one or more other nodes.
Check nodes array instead of node count for each listener.
> Refactor: Improve active listeners check before unsubscription

- build/nodes/firebase-in.html
- src/lib/firebaseNode.ts
- src/lib/types/FirebaseConfigType.ts
- Query Constraint for Listener (see below)
- Correctly detaches the listener (reason explains below) and the verification of active listeners before unsubscription is no longer necessary (#15)
```
Detaches a callback previously attached with the corresponding `on*()` (`onValue`, `onChildAdded`) listener.
Note: This is not the recommended way to remove a listener. Instead, please use the returned callback function from the respective `on*` callbacks.
```
> Feature: Support Query Constraint for Listener

- build/nodes/firebase-get.html
- build/nodes/firebase-in.html
- Unique translation of constraint options when launching Node-RED.
- Checks if the `Child` follows the rules.
- Untick the `Sort?` option erases the values (the table) only if the configuration is saved.
- Tick the `Sort?` option with no constraints saved generates a default line.
- The type of `Value` field is not saved which causes an error displaying the type of it at the next configuration.
- For constraints using `Child` and `Value`, an error reading the properties on the next configuration results in an undefined value for `Child`.
> Fix: `typedInput` for `Query Constraint` container

- build/nodes/firebase-get.html
- build/nodes/firebase-in.html
- build/nodes/locales/en-US/firebase-get.json
- build/nodes/locales/en-US/firebase-in.json
- build/nodes/locales/fr/firebase-get.json
- build/nodes/locales/fr/firebase-in.json
- Child key for Range Queries can be empty (undefined)
- Child key for Range Queries is not saved correctly
> Fix: `validate` and `saveItems` functions for `Child Key` field

- build/nodes/firebase-get.html
- build/nodes/firebase-in.html
- src/lib/firebaseNode.ts
- src/lib/types/FirebaseNodeType.ts
- Saved value of `Value` field does not have the correct type (always string)
- `checkQueryConstraint` accepts now `null` as value for Range Queries
- (Firebase-get) Options `date`, `flow`, `global`, `msg` and `null` have been added
- (Firebase-in) Options `date` and `null` have been added
> Feature: New options for the `Value` field of the `Query Constraints` container

- build/nodes/database.html
- Options allowed are `string`, `number`, `boolean`, `date` and `json`
- Saved value does not have the correct type (always string)
- Validation of Claims (does the value match the type and the key is it allowed)
- A notification is sent if the field value is incorrect
> Improve: Additional Claims Container

- build/nodes/locales/en-US/on-disconnect.html
- build/nodes/locales/en-US/on-disconnect.json
- build/nodes/locales/fr/on-disconnect.html
- build/nodes/locales/fr/on-disconnect.json
- build/nodes/on-disconnect.html
- package.json
- src/lib/databaseNode.ts
- src/lib/onDisconnectNode.ts
- src/lib/types/OnDisconnectConfigType.ts
- src/lib/types/OnDisconnectNodeType.ts
- src/nodes/on-disconnect.ts
- `On Disconnect` Node
The `On Disconnect` node allows you to write or clear data when your client disconnects from the Database server. These updates occur whether your client disconnects cleanly or not, so you can rely on them to clean up data even if a connection is dropped or a client crashes.
Moreover, this node proposes to send a message when the client is connected and/or the client disconnects from the database.
The **Wiki** features this node [here](https://github.com/GogoVega/node-red-contrib-firebase-realtime-database/wiki/on-disconnect) 😉
> Feature: `On Disconnect` Node

- build/nodes/database.html
Fixes #48
`API Key` containing the following character(s) throw an invalid input pattern:
- dashes `-`
- underlines `_` or backward slashes `\`
> Fix: Invalid `API Key` input pattern (#48)

- build/nodes/locales/de/firebase-out.html
- build/nodes/locales/en-US/firebase-out.html
- build/nodes/locales/fr/database.html
- build/nodes/locales/fr/firebase-get.html
- build/nodes/locales/fr/firebase-in.html
- build/nodes/locales/fr/firebase-out.html
- build/nodes/locales/fr/on-disconnect.html
- examples/demo-flow.json
- examples/on-disconnect-flow.json
- src/lib/firebaseNode.ts
- src/lib/onDisconnectNode.ts
- src/lib/types/UtilType.ts
Returns a placeholder value for auto-populating the current timestamp (time since the Unix epoch, in milliseconds) as determined by the Firebase servers.
For example: sending the following message to the `Firebase out` node,
```js
{
payload: "TIMESTAMP",
method: "set",
path: "currentServerTimestamp"
}
```
amounts to:
```js
const timestampRef = ref.child("currentServerTimestamp");
timestampRef.set(ServerValue.TIMESTAMP);
```
Returns a placeholder value that can be used to atomically increment the current database value by the provided delta.
For example: sending the following message to the `Firebase out` node,
```js
{
payload: "INCREMENT 1",
method: "set",
path: "updateIndex"
}
```
amounts to:
```js
const indexRef = ref.child("updateIndex");
indexRef.set(ServerValue.increment(1));
``` …
> Support for built-in `TIMESTAMP` and `increment` server values

- build/nodes/firebase-in.html
- build/nodes/locales/de/firebase-in.html
- build/nodes/locales/de/firebase-in.json
- build/nodes/locales/en-US/firebase-in.html
- build/nodes/locales/en-US/firebase-in.json
- build/nodes/locales/fr/firebase-in.html
- build/nodes/locales/fr/firebase-in.json
- src/lib/firebase-node.ts
- src/lib/ondisconnect-node.ts
- src/lib/types/firebase-config.ts
- src/lib/types/firebase-node.ts
- src/lib/types/ondisconnect-config.ts
- src/lib/types/ondisconnect-node.ts
- src/lib/utils.ts
- src/nodes/firebase-in.ts
Support to dynamically set `Firebase-in` node properties:
- Listener
- Path
- Query Constraints
i.e. This node can be setted to have input and node properties set dynamically from the properties of an incoming message.
> Feature: dynamically set `Firebase-in` node properties

- build/nodes/firebase-get.html
- build/nodes/firebase-in.html
- build/nodes/firebase-out.html
- build/nodes/load-config.html
- build/nodes/locales/de/firebase-get.json
- build/nodes/locales/de/firebase-in.json
- build/nodes/locales/de/load-config.json
- build/nodes/locales/en-US/firebase-get.json
- build/nodes/locales/en-US/firebase-in.json
- build/nodes/locales/en-US/load-config.json
- build/nodes/locales/fr/firebase-get.json
- build/nodes/locales/fr/firebase-in.json
- build/nodes/locales/fr/load-config.json
- build/nodes/on-disconnect.html
- package.json
- resources/common.js
- resources/constraints-container.js
Moved all common methods to resources to remove duplicates.
These methods have been separated into two resources:
- Common
- Query Constraints
The validation functions have become stricter in order to ask the user to redeploy!
I would try to add these changes to the Migration Wizard so that the user doesn't have to do anything anymore
> Refactor: Use resources for editor to remove duplicates

- build/nodes/firebase-get.html
- build/nodes/firebase-in.html
- build/nodes/locales/de/firebase-get.html
- build/nodes/locales/de/firebase-get.json
- build/nodes/locales/de/firebase-in.html
- build/nodes/locales/de/firebase-in.json
- build/nodes/locales/en-US/firebase-get.html
- build/nodes/locales/en-US/firebase-get.json
- build/nodes/locales/en-US/firebase-in.html
- build/nodes/locales/en-US/firebase-in.json
- build/nodes/locales/fr/firebase-get.html
- build/nodes/locales/fr/firebase-get.json
- build/nodes/locales/fr/firebase-in.html
- build/nodes/locales/fr/firebase-in.json
- resources/constraints-container.js
- src/lib/firebase-node.ts
- src/lib/types/firebase-config.ts
Below, what changed for the use of Query Constraints:
- Constraints defined in the node:
- `node.constraint` becomes `node.constraints`
- `node.useConstraint` becomes `node.useConstraints`
- Constraints defined dynamically:
`msg.method` becomes `msg.constraints`
**These changes are non-breaking: your flows will continue to work until you redeploy the changes**
BUT: the node validation will return an error!
> (QueryConstraints) `constraint` and `msg.method` are deprecated

- src/lib/firebase-node.ts
This PR reinforces the initial integration of #51:
- Relax Integer rule to Number
So the regex now accepts a number instead of an integer.
- Add `DECREMENT` keyword
You can now use `DECREMENT 5` instead of `INCREMENT -5`
> (ServerValue) Relax Integer rule to Number and add `DECREMENT` keyword

- resources/common.js
- resources/constraints-container.js
- src/lib/firebase-node.ts
Add `env` (environment variable) field type to:
- `Path` input
- `Child` and `Value` inputs (Query Constraints)
Completes #65.
> Feature: Add `env` field type to `Path`, `Child` and `Value` inputs

- resources/common.js
Introduced in #60, this PR improve it by adding a cache system and bringing it closer to the actual NR autocomplete - there is no longer any suggestion based on the depth of the path, all known paths are suggested.
In addition, `Path` rules has been relaxed which corresponds to current versions (before v0.6).
> Improve the autocomplete of `Path` field

- src/lib/firebase-node.ts
Node-RED v4 introduced a small new feature to add options to the `date` type (TypedInput). It's therefore necessary to get the final value according to the option.
Since v4 and earlier versions of Node-RED support the `date` type in the `RED.util.evaluateNodeProperty` function, let's use it directly.
> Fix the value of the `date` option for the field type

- resources/migration.js
The first beta highlighted that updating the palette requires a restart of Node-RED to load the config-node.
Although the migration can be performed before installation, it's preferable that the installation be completed before then.
To do that, the migration notification will not be issued if the installation notification has been issued.
> Avoid issuing both installation and migration notifications

- build/nodes/firebase-get.html
- build/nodes/firebase-in.html
- build/nodes/firebase-out.html
- build/nodes/on-disconnect.html
This change reflects the "new" standard of putting the Name field first.
> Move all `name` fields to the top of the edit box

- .github/workflows/publish.yml
- resources/migration.js
- scripts/update-required-config-node-version.js
- src/lib/firebase-node.ts
- src/migration/config-node.ts
- src/nodes/load-config.ts
- tsconfig.json
TL;DR - Remove Install Script and replace by the Update Script.
The Install Script was based on the idea that NR might fail to load the Config Node. This script trying to find where the Config Node package was installed and suggest a command to the user to run so that NR could load it. A notification system in the editor also allowed this to be done automatically.
Since NR is able to load it after a reboot (because it does a deep scan) this script is no longer needed.
But, the first tests with the Cloud Firestore palette have highlighted a new problem: when installing the RTDB palette if the Cloud Firestore palette is already installed (or vice versa) NPM installs a new Config Node package inside the package it installs. NR cannot therefore load this new package and will load the existing …
> Check if the required Config Node version is satisfied

- resources/common.js
- src/nodes/load-config.ts
Node-RED crash if autocomplete do a request and fails. Like Permission Denied.
And also:
- Slight rewrite
- Decode path in backend
> Fix autocomplete crash if database get request fails

- resources/first-flow.js
- resources/migration.js
Introduced by #79, the following improvements have been made:
- Prevents the tour from starting while another tour is in progress. (not yet protected into the core)
- Fixes restoration of previously applied palette filter.
- Adds the Firebase icon.
- Adds one step per node to describe it.
Also, for this phase of development, the tour will be loaded from the repo to avoid publishing a new version for each change made.
**As a reminder**: this feature is a demonstrator - it is not currently designed to be used by third-party node developers. If you like it, please let the NR team know so that it can be opened up.
> Improve the `First flow` tour guide

- build/nodes/firebase-in.html
- src/lib/firebase-node.ts
- src/lib/types/firebase-config.ts
If a user wants to use the `env` type of the `Path` field he must set the listener to `use msg.listener` which prevents the listener from being static.
To solve this, all types of the `Path` field are available by default and the node input will be present depending on listener, path and constraints settings.
> Offers all types to the `Path` field by default

- src/lib/firebase-node.ts
- src/lib/ondisconnect-node.ts
Ensure `done` is called to avoid timeout.
By default nodes have no timeout but the `complete` node will not be triggered.
> Avoid Node Messaging timeout

- build/nodes/locales/en-US/load-config.json
- build/nodes/locales/fr/load-config.json
- resources/constraints-container.js
Avoid defining the same constraint twice by marking the select input as invalid.
- Same constraint used
- Same type used
---
> [!NOTE]
> Need Node-RED `4.0.9` to show the tooltip.
> Mark select input as error if constraint already used

- resources/first-flow.js
- resources/migration.js
The `First Flow` tour will be ignored if the settings file contains:
```js
{
editorTheme: {
tours: false
}
}
```
Also fixes an edge case when using RTDB and Firestore simultaneously - concurrent call protection is not aware of the tour loading time.
And finally, telemetry has access to errors generated by the runner.
> Fix and improve the TourGuide runner
