- src/database.html
- src/lib/databaseNode.js
Avoid unnecessary creation of new user in the event of a typo in the email address
> Create a new user only if the option is checked

- build/nodes/database.html
- build/nodes/firebase-get.html
- build/nodes/firebase-in.html
- build/nodes/firebase-out.html
- src/lib/const/FirebaseError.ts
- src/lib/databaseNode.ts
- src/lib/firebaseNode.ts
- src/lib/types/DatabaseConfigType.ts
- src/lib/types/DatabaseNodeType.ts
- src/lib/types/FirebaseConfigType.ts
- src/lib/types/FirebaseNodeType.ts
- src/lib/types/UtilType.ts
- src/lib/utils.ts
- src/nodes/database.ts
- src/nodes/firebase-get.ts
- src/nodes/firebase-in.ts
- src/nodes/firebase-out.ts
- test/firebase-get_spec.js
- test/firebase-in_spec.js
- test/firebase-out_spec.js
- Adds new connection statuses (`No Network` and `Error`).
- Replaced `removeNodeStatus` method with `deregisterNode`.
- Introduction of the `registerNode` and `onError` methods.
The management of the status of the node is done in the `onError` method, indeed this one sends a customized message if the error is known and defines the status of the node (`Error: ` + code) otherwise sends the error as it is and defines the status of the node as `Error`.
> Refactor: Improve node status and error handling

- build/nodes/firebase-get.html
- build/nodes/firebase-in.html
- build/nodes/firebase-out.html
- src/lib/firebaseNode.ts
- src/lib/types/FirebaseConfigType.ts
- src/lib/types/FirebaseNodeType.ts
- (sendMsg) `priority` value to the output message.
- (firebase-out) `setPriority` and `setWithPriority` options.
> Feature: Support for `setPriority` and `setWithPriority` queries

- build/nodes/firebase-get.html
- src/lib/firebaseNode.ts
- src/lib/types/FirebaseConfigType.ts
> Feature: `EditableList` to set query constraint in `firebase-get` node

- build/nodes/database.html
- src/lib/databaseNode.ts
- src/lib/types/DatabaseNodeType.ts
- src/nodes/database.ts
- tsconfig.json
- Uses two new entries for authentication with Private Key
- Drag and drop file to set `Private Key` and `Client Email` entries
- Support Asia (Southeast) Database URL
https://user-images.githubusercontent.com/92022724/216765511-9fe8778e-803f-4168-bb76-6c39791d524c.mov
> Feature: Drag and drop file for Private Key authentication

- .gitignore
- build/nodes/database.html
- build/nodes/firebase-get.html
- build/nodes/firebase-in.html
- build/nodes/firebase-out.html
- build/nodes/locales/en-US/database.html
- build/nodes/locales/en-US/database.json
- build/nodes/locales/en-US/firebase-get.html
- build/nodes/locales/en-US/firebase-get.json
- build/nodes/locales/en-US/firebase-in.html
- build/nodes/locales/en-US/firebase-in.json
- build/nodes/locales/en-US/firebase-out.html
- build/nodes/locales/en-US/firebase-out.json
- build/nodes/locales/fr/database.html
- build/nodes/locales/fr/database.json
- build/nodes/locales/fr/firebase-get.html
- build/nodes/locales/fr/firebase-get.json
- build/nodes/locales/fr/firebase-in.html
- build/nodes/locales/fr/firebase-in.json
- build/nodes/locales/fr/firebase-out.html
- build/nodes/locales/fr/firebase-out.json
[Translation of nodes](https://nodered.org/docs/creating-nodes/i18n).
> Feature: Internationalisation

- build/nodes/firebase-get.html
- build/nodes/locales/en-US/firebase-get.html
- build/nodes/locales/en-US/firebase-get.json
- build/nodes/locales/en-US/firebase-in.html
- build/nodes/locales/fr/firebase-get.html
- build/nodes/locales/fr/firebase-get.json
- build/nodes/locales/fr/firebase-in.html
- src/lib/firebaseNode.ts
- src/lib/types/FirebaseConfigType.ts
- src/lib/types/FirebaseNodeType.ts
- Option to pass through the message
- Send `null` payload if no data for the configured path (#28)
- Message properties for data help
> Feature: Pass through message

- build/nodes/database.html
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
> Fix: Drop frame (icon missing and scroll issue)

- build/nodes/firebase-get.html
- build/nodes/firebase-in.html
- build/nodes/locales/en-US/firebase-get.json
- build/nodes/locales/en-US/firebase-in.json
- build/nodes/locales/fr/firebase-get.json
- build/nodes/locales/fr/firebase-in.json
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
Also add the translation of the `Value` and `Child` fields.
> Improve: The style of `Query Constraints` container

- src/lib/firebaseNode.ts
**You can now use the path as an object**:
Your configured path: `database.path`
Your message contains:
```js
{
database: {
path: "myPath"
}
}
```
Your configured path: `database[msg.topic]`
Your message contains:
```js
{
database: {
path: "myPath"
},
topic: "path"
}
```
> Improve: `msg` option for `Path` field

- build/nodes/locales/de/database.html
- build/nodes/locales/de/database.json
- build/nodes/locales/de/firebase-get.html
- build/nodes/locales/de/firebase-get.json
- build/nodes/locales/de/firebase-in.html
- build/nodes/locales/de/firebase-in.json
- build/nodes/locales/de/firebase-out.html
- build/nodes/locales/de/firebase-out.json
- build/nodes/locales/de/on-disconnect.html
- build/nodes/locales/de/on-disconnect.json
This PR adds German translations. If someone finds a spelling/grammar mistake feel free to correct it. I cannot guarantee that every translated phrase fits in every context it is used in. So just file a PR if you want to have something corrected.
> Translations: German

- build/nodes/locales/de/load-config.json
- build/nodes/locales/en-US/load-config.json
- build/nodes/locales/fr/load-config.json
- resources/common.js
- resources/constraints-container.js
Informs the user of the reason for the input error.
This message is visible by pointing the mouse cursor either on the field or on the red triangle of the node:
- On the field
- On the red triangle
A current limitation of `typedInput` prevents the user from seeing the message if he hover their mouse cursor over the field. The Node-RED team is working on it.
> Enhancement: Validation error message

- build/nodes/firebase-get.html
- build/nodes/firebase-in.html
- build/nodes/locales/de/firebase-get.html
- build/nodes/locales/de/firebase-get.json
- build/nodes/locales/de/firebase-in.html
- build/nodes/locales/de/firebase-in.json
- build/nodes/locales/en-US/firebase-get.html
- build/nodes/locales/en-US/firebase-get.json
- build/nodes/locales/en-US/firebase-in.html
- build/nodes/locales/en-US/firebase-in.json
- build/nodes/locales/fr/firebase-get.html
- build/nodes/locales/fr/firebase-get.json
- build/nodes/locales/fr/firebase-in.html
- build/nodes/locales/fr/firebase-in.json
- resources/common.js
- src/lib/firebase-node.ts
- src/lib/types/firebase-config.ts
A new option has been added to the `Output` field so that the data is in JSON format.
> Feature: JSON data output format

- resources/common.js
- src/lib/firebase-node.ts
- src/lib/ondisconnect-node.ts
- src/lib/types/firebase-config.ts
`flow`, `global` and `jsonata` options has been added to the `Path` field for all nodes.
> Feature: `flow`, `global` and `jsonata` as new `Path` types

- build/nodes/firebase-get.html
- build/nodes/firebase-in.html
- build/nodes/firebase-out.html
- build/nodes/on-disconnect.html
- resources/common.js
- src/nodes/load-config.ts
- src/utils/check-config-node.ts
You can't believe it, it's finally here 🙃
The field helps the user to complete the path as shown in the video below:
https://github.com/GogoVega/node-red-contrib-firebase-realtime-database/assets/92022724/2cd6d195-7355-49b1-9860-cb35675fc4da
> Enhancement: Add `autocomplete` to the `Path` field

- resources/common.js
- resources/constraints-container.js
- src/lib/firebase-node.ts
- src/lib/types/firebase-config.ts
- src/lib/types/firebase-node.ts
QueryConstraints: `msg`, `flow`, `global` and `jsonata` as new types for the `Value` field and the `Child` field
> Feature: (QueryConstraints) New types for the `Value` field and the `Child` field

- build/nodes/firebase-get.html
- build/nodes/firebase-in.html
- build/nodes/firebase-out.html
- build/nodes/on-disconnect.html
- resources/common.js
- resources/constraints-container.js
Sometimes Firebase nodes can appear as unknown type, to resolve this you had to refresh the browser. This PR should resolve that issue.
> Ensure scripts have been loaded

- resources/first-flow.js
- resources/migration.js
This PR introduces the `First flow` tour guide, this is an automated guide that helps new users to learn how to use Firebase nodes.
More specifically, this guide brings the user to import an example flow, configure it and deploy it.
This guide is a first attempt. Feel free to give your feedback to improve it further.
The guide is **launched only once**. UI does not allow to launch it manually (the NR team is working on a guideline to open this functionality to developers).
If you (user) want to launch it manually, go to your browser console and enter the following code:
```js
RED.tourGuide.run("/resources/@gogovega/node-red-contrib-firebase-realtime-database/first-flow.js");
```
> Introduce the `First flow` tour guide

- build/nodes/locales/de/firebase-in.html
- build/nodes/locales/en-US/firebase-in.html
- build/nodes/locales/fr/firebase-in.html
- src/lib/firebase-node.ts
- src/lib/types/firebase-node.ts
Allows `msg.listener` to unsubscribe (only) to data if the keyword used is `reset` and updates the Firebase IN node docs accordingly.
> Allow `msg.listener` to unsubscribe from data

- src/lib/firebase-node.ts
- Firebase IN
- `Subscribed`
- `Unsubscribed`
- Firebase GET & OUT
- `Query Done`
Also fixes persistence of `Permission Denied` status.
> Add new node statuses to improve tracking

- src/lib/firebase-node.ts
Follows #87 and https://github.com/GogoVega/Firebase-Config-Node/pull/19.
- Persists the `Unsubscribed` status.
- Add `Waiting for Subscription...` status to Firebase IN node.
- Replace id by node instance for the `statusListener`.
> Improve the node status and add `Waiting` status

- package-lock.json
- package.json
Apply https://github.com/GogoVega/Firebase-Config-Node/pull/27: `0.x.y` where `x` will be incremented for breaking changes.
> Update the dependency versioning
